export const levels = [
  {
    id: 1,
    name: 'First Sort',
    theme: 'forest',
    description: 'Pick the red gems and place them in the slot!',
    hint: 'REPEAT Forever &rarr; IF Red &rarr; PICK gem &rarr; PLACE in Slot 1',
    conveyorSpeed: 30,
    gemSpawnInterval: 3500,
    gemTypes: [
      { color: 'red', shape: 'circle', weight: 3 },
      { color: 'blue', shape: 'circle', weight: 2 },
    ],
    slots: [
      { id: 0, label: 'Red', acceptColor: 'red', acceptShape: null },
    ],
    availableBlocks: ['if_color', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 3 },
    loseCondition: { type: 'miss_count', count: 8 },
    maxGems: 10,
    starThresholds: [3, 4, 5],
  },
  {
    id: 2,
    name: 'Two Bins',
    theme: 'beach',
    description: 'Sort red gems into Slot 1 and blue gems into Slot 2!',
    hint: 'REPEAT Forever &rarr; IF Red &rarr; PICK &rarr; PLACE 1, then IF Blue &rarr; PICK &rarr; PLACE 2',
    conveyorSpeed: 35,
    gemSpawnInterval: 3200,
    gemTypes: [
      { color: 'red', shape: 'circle', weight: 2 },
      { color: 'blue', shape: 'circle', weight: 2 },
    ],
    slots: [
      { id: 0, label: 'Red', acceptColor: 'red', acceptShape: null },
      { id: 1, label: 'Blue', acceptColor: 'blue', acceptShape: null },
    ],
    availableBlocks: ['if_color', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 5 },
    loseCondition: { type: 'miss_count', count: 4 },
    maxGems: 12,
    starThresholds: [5, 8, 10],
  },
  {
    id: 3,
    name: 'Color Rush',
    theme: 'candy',
    description: 'Three colors, three bins! Sort them all!',
    hint: 'Add an IF block for each color',
    conveyorSpeed: 40,
    gemSpawnInterval: 2800,
    gemTypes: [
      { color: 'red', shape: 'circle', weight: 2 },
      { color: 'blue', shape: 'circle', weight: 2 },
      { color: 'green', shape: 'circle', weight: 2 },
    ],
    slots: [
      { id: 0, label: 'Red', acceptColor: 'red', acceptShape: null },
      { id: 1, label: 'Blue', acceptColor: 'blue', acceptShape: null },
      { id: 2, label: 'Green', acceptColor: 'green', acceptShape: null },
    ],
    availableBlocks: ['if_color', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 6 },
    loseCondition: { type: 'miss_count', count: 4 },
    maxGems: 14,
    starThresholds: [6, 9, 12],
  },
  {
    id: 4,
    name: 'Four Colors',
    theme: 'space',
    description: 'Four colors now! Build a program to sort them all.',
    hint: 'One IF block per color, all inside a REPEAT forever',
    conveyorSpeed: 45,
    gemSpawnInterval: 2600,
    gemTypes: [
      { color: 'red', shape: 'circle', weight: 2 },
      { color: 'blue', shape: 'circle', weight: 2 },
      { color: 'green', shape: 'circle', weight: 2 },
      { color: 'yellow', shape: 'circle', weight: 2 },
    ],
    slots: [
      { id: 0, label: 'Red', acceptColor: 'red', acceptShape: null },
      { id: 1, label: 'Blue', acceptColor: 'blue', acceptShape: null },
      { id: 2, label: 'Green', acceptColor: 'green', acceptShape: null },
      { id: 3, label: 'Yellow', acceptColor: 'yellow', acceptShape: null },
    ],
    availableBlocks: ['if_color', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 8 },
    loseCondition: { type: 'miss_count', count: 4 },
    maxGems: 16,
    starThresholds: [8, 11, 14],
  },
  {
    id: 5,
    name: 'Shape Sorter',
    theme: 'ocean',
    description: 'New challenge! Sort gems by SHAPE instead of color.',
    hint: 'Use the IF shape blocks to match gem shapes',
    conveyorSpeed: 45,
    gemSpawnInterval: 2800,
    gemTypes: [
      { color: 'red', shape: 'circle', weight: 2 },
      { color: 'red', shape: 'diamond', weight: 2 },
      { color: 'red', shape: 'triangle', weight: 2 },
    ],
    slots: [
      { id: 0, label: 'Circles', acceptColor: null, acceptShape: 'circle' },
      { id: 1, label: 'Diamonds', acceptColor: null, acceptShape: 'diamond' },
      { id: 2, label: 'Triangles', acceptColor: null, acceptShape: 'triangle' },
    ],
    availableBlocks: ['if_shape', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 6 },
    loseCondition: { type: 'miss_count', count: 4 },
    maxGems: 14,
    starThresholds: [6, 9, 12],
  },
  {
    id: 6,
    name: 'Shape Challenge',
    theme: 'jungle',
    description: 'Stars and hexagons join the mix! Sort four shapes.',
    hint: 'Add IF blocks for each shape type',
    conveyorSpeed: 50,
    gemSpawnInterval: 2500,
    gemTypes: [
      { color: 'blue', shape: 'circle', weight: 2 },
      { color: 'blue', shape: 'diamond', weight: 2 },
      { color: 'blue', shape: 'star', weight: 2 },
      { color: 'blue', shape: 'hexagon', weight: 2 },
    ],
    slots: [
      { id: 0, label: 'Circles', acceptColor: null, acceptShape: 'circle' },
      { id: 1, label: 'Diamonds', acceptColor: null, acceptShape: 'diamond' },
      { id: 2, label: 'Stars', acceptColor: null, acceptShape: 'star' },
      { id: 3, label: 'Hexagons', acceptColor: null, acceptShape: 'hexagon' },
    ],
    availableBlocks: ['if_shape', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 8 },
    loseCondition: { type: 'miss_count', count: 4 },
    maxGems: 16,
    starThresholds: [8, 11, 14],
  },
  {
    id: 7,
    name: 'Color & Shape',
    theme: 'volcano',
    description: 'Sort by BOTH color AND shape! Red circles, blue diamonds, green triangles. Some gems won\'t match any bin — let them pass!',
    hint: 'Use the IF color AND shape blocks for precise sorting',
    conveyorSpeed: 50,
    gemSpawnInterval: 2500,
    gemTypes: [
      { color: 'red', shape: 'circle', weight: 2 },
      { color: 'blue', shape: 'diamond', weight: 2 },
      { color: 'green', shape: 'triangle', weight: 2 },
      { color: 'red', shape: 'diamond', weight: 1 },
      { color: 'blue', shape: 'circle', weight: 1 },
    ],
    slots: [
      { id: 0, label: 'Red Circle', acceptColor: 'red', acceptShape: 'circle' },
      { id: 1, label: 'Blue Diamond', acceptColor: 'blue', acceptShape: 'diamond' },
      { id: 2, label: 'Green Triangle', acceptColor: 'green', acceptShape: 'triangle' },
    ],
    availableBlocks: ['if_color_and_shape', 'if_color', 'if_shape', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 6 },
    loseCondition: { type: 'miss_count', count: 8 },
    maxGems: 16,
    starThresholds: [6, 8, 10],
  },
  {
    id: 8,
    name: 'Speed Sort',
    theme: 'arctic',
    description: 'The belt is speeding up! Sort gems quickly!',
    hint: 'Keep your program efficient — fewer blocks = faster sorting',
    conveyorSpeed: 65,
    gemSpawnInterval: 2000,
    gemTypes: [
      { color: 'red', shape: 'circle', weight: 2 },
      { color: 'blue', shape: 'diamond', weight: 2 },
      { color: 'green', shape: 'star', weight: 2 },
      { color: 'yellow', shape: 'triangle', weight: 2 },
    ],
    slots: [
      { id: 0, label: 'Red Circle', acceptColor: 'red', acceptShape: 'circle' },
      { id: 1, label: 'Blue Diamond', acceptColor: 'blue', acceptShape: 'diamond' },
      { id: 2, label: 'Green Star', acceptColor: 'green', acceptShape: 'star' },
      { id: 3, label: 'Yellow Triangle', acceptColor: 'yellow', acceptShape: 'triangle' },
    ],
    availableBlocks: ['if_color_and_shape', 'if_color', 'if_shape', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 8 },
    loseCondition: { type: 'miss_count', count: 5 },
    maxGems: 18,
    starThresholds: [8, 12, 16],
  },
  {
    id: 9,
    name: 'Master Sorter',
    theme: 'desert',
    description: 'Five bins, mixed gems, faster belt. Show your skills!',
    hint: 'Think carefully about your IF conditions',
    conveyorSpeed: 70,
    gemSpawnInterval: 1800,
    gemTypes: [
      { color: 'red', shape: 'circle', weight: 2 },
      { color: 'blue', shape: 'diamond', weight: 2 },
      { color: 'green', shape: 'star', weight: 2 },
      { color: 'yellow', shape: 'triangle', weight: 2 },
      { color: 'purple', shape: 'hexagon', weight: 2 },
    ],
    slots: [
      { id: 0, label: 'Red Circle', acceptColor: 'red', acceptShape: 'circle' },
      { id: 1, label: 'Blue Diamond', acceptColor: 'blue', acceptShape: 'diamond' },
      { id: 2, label: 'Green Star', acceptColor: 'green', acceptShape: 'star' },
      { id: 3, label: 'Yellow Triangle', acceptColor: 'yellow', acceptShape: 'triangle' },
      { id: 4, label: 'Purple Hexagon', acceptColor: 'purple', acceptShape: 'hexagon' },
    ],
    availableBlocks: ['if_color_and_shape', 'if_color', 'if_shape', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 10 },
    loseCondition: { type: 'miss_count', count: 5 },
    maxGems: 20,
    starThresholds: [10, 14, 18],
  },
  {
    id: 10,
    name: 'Grand Champion',
    theme: 'crystal',
    description: 'The ultimate challenge! Maximum speed, all gem types, five bins. Some gems are distractors — let them pass!',
    hint: 'You need a perfect program — sort every matching gem!',
    conveyorSpeed: 80,
    gemSpawnInterval: 1500,
    gemTypes: [
      { color: 'red', shape: 'star', weight: 2 },
      { color: 'blue', shape: 'circle', weight: 2 },
      { color: 'green', shape: 'hexagon', weight: 2 },
      { color: 'yellow', shape: 'diamond', weight: 2 },
      { color: 'purple', shape: 'triangle', weight: 2 },
      { color: 'red', shape: 'circle', weight: 1 },
      { color: 'blue', shape: 'diamond', weight: 1 },
    ],
    slots: [
      { id: 0, label: 'Red Star', acceptColor: 'red', acceptShape: 'star' },
      { id: 1, label: 'Blue Circle', acceptColor: 'blue', acceptShape: 'circle' },
      { id: 2, label: 'Green Hexagon', acceptColor: 'green', acceptShape: 'hexagon' },
      { id: 3, label: 'Yellow Diamond', acceptColor: 'yellow', acceptShape: 'diamond' },
      { id: 4, label: 'Purple Triangle', acceptColor: 'purple', acceptShape: 'triangle' },
    ],
    availableBlocks: ['if_color_and_shape', 'if_color', 'if_shape', 'pick_gem', 'place_in_slot', 'repeat', 'wait'],
    winCondition: { type: 'sort_count', count: 10 },
    loseCondition: { type: 'miss_count', count: 8 },
    maxGems: 22,
    starThresholds: [10, 13, 16],
  },
];
