export const levels = [
  {
    id: 1,
    name: 'First Sort',
    theme: 'forest',
    description: 'Pick the matching gems and place them in the slot!',
    hint: 'REPEAT Forever &rarr; IF matching color &rarr; PICK gem &rarr; PLACE in Slot 1',
    conveyorSpeed: 40,
    gemSpawnInterval: 3500,
    sortBy: 'color',
    numSlots: 1,
    numDistractors: 1,
    gemWeight: 3,
    distractorWeight: 2,
    availableBlocks: ['if_color', 'if_shape', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 3 },
    loseCondition: { type: 'miss_count', count: 8 },
    maxGems: 10,
    starThresholds: [3, 4, 5],
  },
  {
    id: 2,
    name: 'Two Bins',
    theme: 'beach',
    description: 'Two bins now! Sort each gem type into the matching slot!',
    hint: 'REPEAT Forever &rarr; check each color &rarr; PICK &rarr; PLACE in matching slot',
    conveyorSpeed: 45,
    gemSpawnInterval: 3200,
    sortBy: 'color',
    numSlots: 2,
    numDistractors: 0,
    gemWeight: 2,
    distractorWeight: 0,
    availableBlocks: ['if_color', 'if_shape', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 5 },
    loseCondition: { type: 'miss_count', count: 4 },
    maxGems: 12,
    starThresholds: [5, 8, 10],
  },
  {
    id: 3,
    name: 'Color Rush',
    theme: 'candy',
    description: 'Three gem types! Match each to the right slot!',
    hint: 'Add an IF block for each gem type',
    conveyorSpeed: 55,
    gemSpawnInterval: 2800,
    sortBy: 'color',
    numSlots: 3,
    numDistractors: 0,
    gemWeight: 2,
    distractorWeight: 0,
    availableBlocks: ['if_color', 'if_shape', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 6 },
    loseCondition: { type: 'miss_count', count: 4 },
    maxGems: 14,
    starThresholds: [6, 9, 12],
  },
  {
    id: 4,
    name: 'Four Colors',
    theme: 'space',
    description: 'Four gem types! Each slot shows what it needs.',
    hint: 'One IF block per gem type, all inside a REPEAT forever',
    conveyorSpeed: 60,
    gemSpawnInterval: 2600,
    sortBy: 'color',
    numSlots: 4,
    numDistractors: 0,
    gemWeight: 2,
    distractorWeight: 0,
    availableBlocks: ['if_color', 'if_shape', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 8 },
    loseCondition: { type: 'miss_count', count: 4 },
    maxGems: 16,
    starThresholds: [8, 11, 14],
  },
  {
    id: 5,
    name: 'Shape Sorter',
    theme: 'ocean',
    description: 'Same color, different shapes! Sort by SHAPE now!',
    hint: 'Use the IF shape blocks to match gem shapes',
    conveyorSpeed: 60,
    gemSpawnInterval: 2800,
    sortBy: 'shape',
    numSlots: 3,
    numDistractors: 0,
    gemWeight: 2,
    distractorWeight: 0,
    availableBlocks: ['if_shape', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 6 },
    loseCondition: { type: 'miss_count', count: 4 },
    maxGems: 14,
    starThresholds: [6, 9, 12],
  },
  {
    id: 6,
    name: 'Shape Challenge',
    theme: 'jungle',
    description: 'Four shapes to sort! Can you handle them all?',
    hint: 'Add IF blocks for each shape type',
    conveyorSpeed: 65,
    gemSpawnInterval: 2500,
    sortBy: 'shape',
    numSlots: 4,
    numDistractors: 0,
    gemWeight: 2,
    distractorWeight: 0,
    availableBlocks: ['if_shape', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 8 },
    loseCondition: { type: 'miss_count', count: 4 },
    maxGems: 16,
    starThresholds: [8, 11, 14],
  },
  {
    id: 7,
    name: 'Color & Shape',
    theme: 'volcano',
    description: 'Sort by BOTH color AND shape! Some gems won\'t match any bin — let them pass!',
    hint: 'Use the IF color AND shape blocks for precise sorting',
    conveyorSpeed: 65,
    gemSpawnInterval: 2500,
    sortBy: 'color_and_shape',
    numSlots: 3,
    numDistractors: 2,
    gemWeight: 2,
    distractorWeight: 1,
    availableBlocks: ['if_color_and_shape', 'if_color', 'if_shape', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 6 },
    loseCondition: { type: 'miss_count', count: 8 },
    maxGems: 16,
    starThresholds: [6, 8, 10],
  },
  {
    id: 8,
    name: 'Speed Sort',
    theme: 'arctic',
    description: 'The belt is speeding up! Sort gems quickly!',
    hint: 'Keep your program efficient — fewer blocks = faster sorting',
    conveyorSpeed: 85,
    gemSpawnInterval: 2000,
    sortBy: 'color_and_shape',
    numSlots: 4,
    numDistractors: 0,
    gemWeight: 2,
    distractorWeight: 0,
    availableBlocks: ['if_color_and_shape', 'if_color', 'if_shape', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 8 },
    loseCondition: { type: 'miss_count', count: 5 },
    maxGems: 18,
    starThresholds: [8, 12, 16],
  },
  {
    id: 9,
    name: 'Master Sorter',
    theme: 'desert',
    description: 'Five bins, random gems, faster belt. Show your skills!',
    hint: 'Think carefully about your IF conditions',
    conveyorSpeed: 90,
    gemSpawnInterval: 1800,
    sortBy: 'color_and_shape',
    numSlots: 5,
    numDistractors: 0,
    gemWeight: 2,
    distractorWeight: 0,
    availableBlocks: ['if_color_and_shape', 'if_color', 'if_shape', 'pick_gem', 'place_in_slot', 'repeat'],
    winCondition: { type: 'sort_count', count: 10 },
    loseCondition: { type: 'miss_count', count: 5 },
    maxGems: 20,
    starThresholds: [10, 14, 18],
  },
  {
    id: 10,
    name: 'Grand Champion',
    theme: 'crystal',
    description: 'The ultimate challenge! Maximum speed, random gems, five bins. Some gems are distractors — let them pass!',
    hint: 'You need a perfect program — sort every matching gem!',
    conveyorSpeed: 105,
    gemSpawnInterval: 1500,
    sortBy: 'color_and_shape',
    numSlots: 5,
    numDistractors: 2,
    gemWeight: 2,
    distractorWeight: 1,
    availableBlocks: ['if_color_and_shape', 'if_color', 'if_shape', 'pick_gem', 'place_in_slot', 'repeat', 'wait'],
    winCondition: { type: 'sort_count', count: 10 },
    loseCondition: { type: 'miss_count', count: 8 },
    maxGems: 22,
    starThresholds: [10, 13, 16],
  },
];
